feat: add using thread

diff --git a/.github/workflows/auto-pr-settings.yml b/.github/workflows/auto-pr-settings.yml
--- a/.github/workflows/auto-pr-settings.yml
+++ b/.github/workflows/auto-pr-settings.yml
@@ -143,4 +143,14 @@ jobs:
                 .blocks[3].elements[0].text.text |= sub("{{BUTTON_TEXT}}"; $button_text) |
                 .blocks[3].elements[0].url |= sub("{{PR_LINK}}"; $pr_link)')
 
-          curl -X POST -H 'Content-type: application/json' --data "$SLACK_MESSAGE" ${{ secrets.SLACK_WEBHOOK_URL }}
+          RESPONSE=$(curl -s -X POST -H 'Content-type: application/json' --data "$SLACK_MESSAGE" ${{ secrets.SLACK_WEBHOOK_URL }})
+          THREAD_TS=$(echo $RESPONSE | jq -r '.ts')
+
+          echo "THREAD_TS=$THREAD_TS" >> $GITHUB_ENV
+
+          if [[ -z "$THREAD_TS" ]]; then
+            echo "Failed to send Slack message."
+            exit 1
+          fi
+
+          echo "${{ github.event.pull_request.number }}=$THREAD_TS" >> thread_ts_map.txt
